version: "3.9"
services:
  app:
    container_name: PriceService
    command: java -jar target/PriceService-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
    expose:
      - 8090
    volumes:
      - ./:/app/app
    networks:
      - services
    restart: unless-stopped

networks:
  services:
    name: Knightly
    external: true